INSERT INTO product_model(name, price) VALUES ('Bike','99.99')
INSERT INTO product_model(name, price) VALUES ('Boat','15000.0')
INSERT INTO product_model(name, price) VALUES ('Ship','258000.99')
INSERT INTO product_model(name, price) VALUES ('Car','35500.66')
INSERT INTO product_model(name, price) VALUES ('Bus','250000.55')
INSERT INTO product_model(name, price) VALUES ('Shoes','99.99')
